/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.calculator.fee;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

public class Application {

    final static Logger LOGGER = LoggerFactory.getLogger(GenerateReport.class);


    public static void main(String[] args) {

        //0. Read Csv file
        TransactionReader transactionReader = new CsvTransactionReader();
        try {
            //1. Read file
            List<Transaction> transactions = transactionReader.read(args[0]);

            //2. If found Record
            if(!transactions.isEmpty()) {

                //3. Create Feecalculator
                FeeCalculatorImpl feeCalculator = new FeeCalculatorImpl();

                //4. Inject FeeCalculator in to GenerateReport
                GenerateReport generateReport = new GenerateReport(feeCalculator);

                try (PrintWriter writer = new PrintWriter(new File("Sample_Output.csv"))) {
                    //Return CSV as String tobe written in file
                    writer.write(generateReport.generateReport(transactions));
                }
            } else {
                LOGGER.info("No Transaction record found. in file : {}", args[0]);
            }
        } catch (IOException e) {
            LOGGER.error("Input Data.csv not found in current folder. Please Place 'Input Data.csv' in  current folder");
        }
    }



}
